name: quan_ly_cong_viec_app
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Mở rộng khoảng tương thích sdk

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1 
  flutter_secure_storage: ^9.2.2 
  # SỬA LỖI: Nâng cấp intl để khớp với yêu cầu của Flutter SDK
  intl: ^0.20.2
  table_calendar: ^3.1.2 
  provider: ^6.1.2 
  shared_preferences: ^2.2.3
  # SỬA LỖI: Nâng cấp awesome_notifications để tương thích với intl mới
  awesome_notifications: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

