name: quan_ly_cong_viec_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ĐÃ XÓA flutter_localizations

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2 # Giữ phiên bản đúng
  table_calendar: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  awesome_notifications: ^0.10.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # ĐÃ XÓA generate: true